server:
  port: 8081
spring:
  application:
    name: spring-rest-crop
  main:
    banner-mode: off

email: yaml@mkyong.com
thread-pool: 10

wordpress:
  menus:
    - title: Home
      name: Home
      path: /
    - title: About
      name: About
      path: /about
  themes:
    default-folder: /wp-content/themes/mkyong
  servers:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3

---
example:
  datasource:
    url: jdbc:mysql://localhost/example
    username: local-user
    password: local-password

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${example.datasource.url}
    username: ${example.datasource.username}
    password: ${example.datasource.password}
---
spring:
  config:
    activate:
      on-profile: pre-prod
  datasource:
    url: ${example.datasource.url}
    username: ${example.datasource.username}
    password: ${example.datasource.password}