apiVersion: v1
kind: Service
metadata:
  name: spring-rest-crop
  namespace: spring-boot-examples
spec:
  ports:
    - name: spring-rest-crop
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: spring-rest-crop
  type: ClusterIP
#type: NodePort