apiVersion: v1
kind: Service
metadata:
  name: spring-crop-service
  namespace: spring-practiced
spec:
  type: NodePort
  selector:
    app: spring-rest-crop
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 32222
